# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment


on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.Azure_CREDENTIALS }}
          
      - name: Deploy Resource Group githubactions-rg 
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription  
          subscriptionId: 11fe335c-5047-42c8-9362-cdd3871da39b 
          region: West Europe
          template: ./arm-templates/resourcegroup.json
          deploymentName: rg-githubactions
  
     